import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-xl font-bold">Hello world!</h1>
        <div className="grid grid-cols-4 gap-4">
          <div className="bg-black">01</div>

          <div className="bg-black">09</div>
        </div>
      </main>
    </div>
  );
};

export default Home;
