import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.scss";
import axios from "axios";
import { useState, useEffect } from "react";
import Bookmark from "../../components/Bookmark.component";
import Banner from "../../components/Banner.component";
import Header from "../../components/Header.component";

interface Attributes {
  url: string;
  description?: string;
  title?: string;
}
interface BookmarksResponse {
  attributes: Attributes;
}

const AdminPage: NextPage = () => {
  const url = "http://api.digitalbytes.com:1337/api";
  const [bookmarks, setBookmarks] = useState<Array<BookmarksResponse>>();

  useEffect(() => {
    axios.get(`${url}/bookmarks`).then((response) => {
      console.log(response.data.data);
      setBookmarks(response.data.data);
    });
  }, []);

  if (!bookmarks) return null;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <Header />
        <Banner label="You are viewing this page as an admin"></Banner>
        <div className="mt-4 grid lg:grid-cols-3 sm:grid-cols-1 sm:gap-1 gap-4">
        <i className="far fa-edit"></i>
          {Boolean(bookmarks.length > 0) &&
            bookmarks.map((b, i) => {
              console.log(b);
              return (
                <Bookmark
                  key={i}
                  isAdmin={true}
                  url={b.attributes.url}
                  title={b.attributes.title}
                  description={b.attributes.description}
                ></Bookmark>
              );
            })}
        </div>
      </main>
    </div>
  );
};

export default AdminPage;
