import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.scss";

const AdminPage: NextPage = () => {
  const url = "http://api.digitalbytes.com:1337/api";


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <div className="mt-8">
          <h1 className="text-3xl font-bold">Hyper Genius</h1>
          <p>A byte is a unit of digital information.</p>
        </div>
        <div className="mt-4 grid lg:grid-cols-3 sm:grid-cols-1 sm:gap-1 gap-4">
        
        </div>
      </main>
    </div>
  );
};

export default AdminPage;
